@startuml
  title 修改银行卡密码活动图

 (*) --> 开始



  开始-->点击安全概述
  点击安全概述->立刻完成
  if "判断安全状况" then
    -->[隐患] "修改密码"
    -down-> 结束
  else
    -->[危险] "修改密保"
    -down-> 结束
  endif



  开始-->点击修改密码
   if "是否设置密保" then
      -->[N] "设置密保"
      -->点击修改密码
    else
      -->[Y] "输入验证密保"
      if "密保是否正确" then
        -->[Y] 提交验证密保
        -down-> 结束
      else
        -up->[N] "输入验证密保"
       endif
    endif



    开始-->点击常见欺骗
    点击常见欺骗-->常见欺诈



    开始-->点击修改密保
     if "是否设置密保" then
        -->[N] "输入密保问题"
        --> "提交密保问题"
        -down-> 结束
      else
        -->[Y] "输入原密保问题"
         if "密保问题是否正确" then
         -->[Y] "提交密保"
         --> "输入新密保"
         --> "提交新密保"
         -down-> 结束
         else
         -->[N] "输入原密保问题"
        -down-> 结束
      endif

@enduml